# Environment Configuration
# Updated via Settings UI

SOURCE_SFDX_USERNAME_LABEL.dev=AU-MasterCatalogDev
SOURCE_SFDX_USERNAME.dev=rocco.sorrentino@amplifonapac.com.mastcatdev
SOURCE_SFDX_ALIAS.dev=AU-MasterCatalogDev
SOURCE_SFDX_URL.dev=https://myamplifonglobal--mastcatdev.sandbox.my.salesforce.com

#TARGET_SFDX_USERNAME_LABEL.dev=AU-SymportingDev
#TARGET_SFDX_USERNAME.dev=rocco.sorrentino@amplifonapac.com.symporting
#TARGET_SFDX_ALIAS.dev=AU-SymportingDev
#TARGET_SFDX_URL.dev=https://myamplifonglobal--symporting.sandbox.my.salesforce.com

TARGET_SFDX_USERNAME_LABEL.dev=AU-FULLUAT01
TARGET_SFDX_USERNAME.dev=rocco.sorrentino@amplifonapac.com.fulluat01
TARGET_SFDX_ALIAS.dev=AU-FULLUAT01
TARGET_SFDX_URL.dev=https://myamplifonglobal--fulluat01.sandbox.my.salesforce.com/


SOURCE_SFDX_USERNAME_LABEL.uat=AU-MasterCatalogDev
SOURCE_SFDX_USERNAME.uat=rocco.sorrentino@amplifonapac.com.mastcatdev
SOURCE_SFDX_ALIAS.uat=AU-MasterCatalogDev
SOURCE_SFDX_URL.uat=https://myamplifonglobal--mastcatdev.sandbox.my.salesforce.com
TARGET_SFDX_USERNAME_LABEL.uat=AU-PRUTUAT01
TARGET_SFDX_USERNAME.uat=rocco.sorrentino@amplifonapac.com.prtuat01
TARGET_SFDX_ALIAS.uat=AU-PRUTUAT01
TARGET_SFDX_URL.uat=https://myamplifonglobal--prtuat01.sandbox.my.salesforce.com/

SOURCE_SFDX_USERNAME_LABEL.prod=
SOURCE_SFDX_USERNAME.prod=
SOURCE__SFDX_ALIAS.prod=
SOURCE__SFDX_URL.prod=
TARGET_SFDX_USERNAME_LABEL.prod=AU-FULLUAT01
TARGET_SFDX_USERNAME.prod=rocco.sorrentino@amplifonapac.com.fulluat01
TARGET_SFDX_ALIAS.prod=AU-FULLUAT01
TARGET_SFDX_URL.prod=https://myamplifonglobal--fulluat01.sandbox.my.salesforce.com/